stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-nginx-image .

deploy_container:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose up -d
