name: Docker Build and Run

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-nginx ./task4-pipeline

    - name: Run Docker container
      run: |
        docker compose -f ./task4-pipeline/docker-compose.yml up -d
